import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Star,
  MessageSquarePlus,
  CheckCircle2,
  X,
  ChevronLeft,
  ChevronRight,
  MapPin,
  Calendar,
  Sparkles,
  Quote,
} from "lucide-react";
import { ProductReview } from "../../types/productDetails";
import {
  getReviewsForProduct,
  addReviewForProduct,
  computeRatingStats,
  getAutoGeneratedReviews,
  RatingStats,
} from "../../lib/reviewsStorage";

interface ProductReviewsSectionProps {
  productId: string;
  productName: string;
  onStatsChange?: (stats: RatingStats) => void;
}

function parseCustomerNameAndArea(fullName: string): { name: string; area: string } {
  const match = fullName.match(/^(.*?)\s*\((.*?)\)$/);
  if (match) {
    return { name: match[1].trim(), area: match[2].trim() };
  }
  return { name: fullName, area: "Maharajganj" };
}

export default function ProductReviewsSection({
  productId,
  productName,
  onStatsChange,
}: ProductReviewsSectionProps) {
  const [reviews, setReviews] = useState<ProductReview[]>(() =>
    getAutoGeneratedReviews(productId)
  );
  const [loading, setLoading] = useState(false);
  const [isWriteModalOpen, setIsWriteModalOpen] = useState(false);
  const [activeReviewIndex, setActiveReviewIndex] = useState(0);

  const isHoveredRef = useRef(false);
  const touchStartX = useRef<number | null>(null);

  // Form State
  const [reviewerName, setReviewerName] = useState("");
  const [reviewerArea, setReviewerArea] = useState("Maharajganj");
  const [selectedRating, setSelectedRating] = useState<number>(5);
  const [hoverRating, setHoverRating] = useState<number | null>(null);
  const [reviewContent, setReviewContent] = useState("");
  const [formError, setFormError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Load reviews whenever productId changes
  useEffect(() => {
    let isMounted = true;
    setLoading(true);

    getReviewsForProduct(productId).then((data) => {
      if (isMounted) {
        const top10 = data.slice(0, 10);
        setReviews(top10);
        setLoading(false);
        const stats = computeRatingStats(top10);
        if (onStatsChange) {
          onStatsChange(stats);
        }
      }
    });

    return () => {
      isMounted = false;
    };
  }, [productId]);

  // Auto-scroll 1 by 1 review every 4 seconds as requested
  useEffect(() => {
    if (reviews.length <= 1) return;

    const interval = setInterval(() => {
      if (isHoveredRef.current) return;
      setActiveReviewIndex((prev) => (prev + 1) % reviews.length);
    }, 4000);

    return () => clearInterval(interval);
  }, [reviews.length]);

  const handlePrev = () => {
    setActiveReviewIndex((prev) => (prev === 0 ? reviews.length - 1 : prev - 1));
  };

  const handleNext = () => {
    setActiveReviewIndex((prev) => (prev === reviews.length - 1 ? 0 : prev + 1));
  };

  const scrollToReview = (index: number) => {
    setActiveReviewIndex(index);
  };

  // Touch Swipe Handlers for Mobile
  const handleTouchStart = (e: React.TouchEvent) => {
    isHoveredRef.current = true;
    touchStartX.current = e.touches[0].clientX;
  };

  const handleTouchEnd = (e: React.TouchEvent) => {
    if (touchStartX.current !== null) {
      const diffX = touchStartX.current - e.changedTouches[0].clientX;
      if (diffX > 40) {
        handleNext();
      } else if (diffX < -40) {
        handlePrev();
      }
    }
    touchStartX.current = null;
    setTimeout(() => {
      isHoveredRef.current = false;
    }, 3000);
  };

  const stats = computeRatingStats(reviews);

  const handleSubmitReview = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError("");

    if (!reviewerName.trim()) {
      setFormError("Please enter your name.");
      return;
    }
    if (!selectedRating || selectedRating < 1 || selectedRating > 5) {
      setFormError("Please select a rating between 1 and 5 stars.");
      return;
    }
    if (!reviewContent.trim()) {
      setFormError("Please write a few words about your experience with this product.");
      return;
    }

    setSubmitting(true);
    try {
      const formattedNameWithArea = `${reviewerName.trim()} (${reviewerArea})`;
      const created = await addReviewForProduct(productId, {
        customerName: formattedNameWithArea,
        rating: selectedRating,
        reviewText: reviewContent,
      });

      const updatedReviews = [created, ...reviews.filter((r) => r.id !== created.id)].slice(0, 10);
      setReviews(updatedReviews);
      const updatedStats = computeRatingStats(updatedReviews);
      if (onStatsChange) {
        onStatsChange(updatedStats);
      }

      // Reset form and close modal
      setReviewerName("");
      setSelectedRating(5);
      setReviewContent("");
      setIsWriteModalOpen(false);
      scrollToReview(0);
    } catch (err) {
      setFormError("Failed to save your review. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  const ratingLabels: Record<number, string> = {
    1: "Poor",
    2: "Fair",
    3: "Good",
    4: "Very Good",
    5: "Excellent",
  };

  const allowedAreas = [
    "Maharajganj",
    "Basantpur",
    "Ekma",
    "Chhapra",
    "Patna",
    "Siwan",
    "Gopalganj",
  ];

  return (
    <div
      id="customer-reviews"
      className="w-full scroll-mt-28 mt-12 pt-8 border-t border-slate-200"
    >
      {/* Header & Write Review Action */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-black text-orange-600 uppercase tracking-widest bg-orange-50 border border-orange-200/70 px-2.5 py-0.5 rounded-md">
              10 VERIFIED RATINGS
            </span>
            <span className="text-xs font-semibold text-slate-400">
              • Direct Customer Feedback
            </span>
          </div>
          <h3 className="text-2xl sm:text-3xl font-black font-display text-slate-900 tracking-tight">
            Customer Reviews ({stats.average.toFixed(1)} ★)
          </h3>
          <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
            Verified customer ratings and authentic product feedback.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          {/* 1-by-1 Navigation Buttons */}
          <div className="flex items-center gap-1.5 bg-slate-100 p-1 rounded-xl border border-slate-200/80">
            <button
              onClick={handlePrev}
              className="p-2 rounded-lg bg-white shadow-xs hover:bg-orange-500 hover:text-white text-slate-700 transition-all cursor-pointer"
              title="Previous Review"
              aria-label="Previous Review"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <span className="text-xs font-mono font-bold px-2 text-slate-700 min-w-[50px] text-center">
              {activeReviewIndex + 1} / {reviews.length}
            </span>
            <button
              onClick={handleNext}
              className="p-2 rounded-lg bg-white shadow-xs hover:bg-orange-500 hover:text-white text-slate-700 transition-all cursor-pointer"
              title="Next Review"
              aria-label="Next Review"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>

          <button
            onClick={() => {
              setFormError("");
              setIsWriteModalOpen(true);
            }}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-orange-600 text-white font-extrabold text-xs sm:text-sm shadow-sm transition-all duration-200 cursor-pointer active:scale-95"
          >
            <MessageSquarePlus className="w-4 h-4" />
            <span className="hidden sm:inline">Write a Review</span>
            <span className="sm:hidden">Review</span>
          </button>
        </div>
      </div>

      {/* Rating Score Summary Card */}
      <div className="bg-white rounded-3xl p-5 sm:p-6 border border-slate-200/80 shadow-xs mb-6 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="flex items-baseline gap-1">
            <span className="text-4xl sm:text-5xl font-black font-display text-slate-900 tracking-tight">
              {stats.average.toFixed(1)}
            </span>
            <span className="text-slate-400 text-base font-bold">/ 5</span>
          </div>

          <div className="flex flex-col">
            <div className="flex items-center gap-1 text-amber-400">
              {[1, 2, 3, 4, 5].map((s) => (
                <Star
                  key={s}
                  className={`w-4 h-4 ${
                    s <= Math.round(stats.average)
                      ? "fill-amber-400 text-amber-400"
                      : "text-slate-200"
                  }`}
                />
              ))}
            </div>
            <span className="text-xs font-semibold text-slate-600 mt-0.5">
              10 Verified Ratings (100% Genuine)
            </span>
          </div>
        </div>

        {/* Verified Trust Badge */}
        <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-emerald-50 border border-emerald-200/70 text-emerald-800 text-xs font-bold">
          <CheckCircle2 className="w-4 h-4 text-emerald-600" />
          <span>100% Genuine Verified Buyer Feedback</span>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* 1-BY-1 REVIEWS SHOWCASE (AUTO-SCROLLING EVERY 4 SECONDS) */}
      {/* ========================================================================= */}
      <div
        className="relative w-full"
        onMouseEnter={() => {
          isHoveredRef.current = true;
        }}
        onMouseLeave={() => {
          isHoveredRef.current = false;
        }}
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
      >
        {loading ? (
          <div className="w-full text-center py-16 text-slate-400 text-sm font-medium bg-white rounded-3xl border border-slate-200">
            Loading reviews...
          </div>
        ) : reviews.length === 0 ? (
          <div className="w-full text-center py-16 text-slate-400 text-sm font-medium bg-white rounded-3xl border border-slate-200">
            No reviews yet. Be the first to review!
          </div>
        ) : (
          (() => {
            const currentReview = reviews[activeReviewIndex] || reviews[0];
            const { name: parsedName, area: parsedArea } = parseCustomerNameAndArea(
              currentReview.customerName
            );

            return (
              <div className="relative bg-white rounded-3xl p-6 sm:p-8 md:p-10 border border-slate-200 shadow-sm overflow-hidden group">
                {/* 4-second auto-scroll animated progress line */}
                <div className="absolute top-0 left-0 right-0 h-1 bg-slate-100 overflow-hidden">
                  <motion.div
                    key={activeReviewIndex}
                    initial={{ width: "0%" }}
                    animate={{ width: "100%" }}
                    transition={{ duration: 4, ease: "linear" }}
                    className="h-full bg-gradient-to-r from-orange-500 to-amber-500"
                  />
                </div>

                <AnimatePresence mode="wait">
                  <motion.div
                    key={currentReview.id || activeReviewIndex}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    transition={{ duration: 0.35, ease: "easeInOut" }}
                    className="flex flex-col gap-6"
                  >
                    {/* Top Row: Review Badge & Rating */}
                    <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-slate-100">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-black tracking-wider uppercase bg-orange-100 text-orange-800 px-3 py-1 rounded-full flex items-center gap-1.5">
                          Review #{activeReviewIndex + 1}
                        </span>
                        <span className="text-xs font-bold text-slate-400 font-mono">
                          of {reviews.length}
                        </span>
                      </div>

                      <div className="flex items-center gap-3">
                        <div className="flex items-center gap-1 bg-amber-50 px-3 py-1 rounded-full border border-amber-200/60">
                          <div className="flex items-center text-amber-400">
                            {[1, 2, 3, 4, 5].map((s) => (
                              <Star
                                key={s}
                                className={`w-4 h-4 ${
                                  s <= currentReview.rating
                                    ? "fill-amber-400 text-amber-400"
                                    : "text-slate-200"
                                }`}
                              />
                            ))}
                          </div>
                          <span className="text-xs font-black text-amber-900 font-mono ml-1">
                            {currentReview.rating}.0
                          </span>
                        </div>

                        <span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-200/60">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                          <span>Verified Buyer</span>
                        </span>
                      </div>
                    </div>

                    {/* Middle: Review Quote */}
                    <div className="relative bg-slate-50/80 p-5 sm:p-6 rounded-2xl border border-slate-100">
                      <Quote className="w-6 h-6 text-orange-400/60 mb-2" />
                      <p className="text-base sm:text-lg text-slate-800 leading-relaxed font-normal not-italic">
                        "{currentReview.reviewText}"
                      </p>
                    </div>

                    {/* Bottom: Customer profile & controls */}
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-2">
                      <div className="flex items-center gap-3.5">
                        <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-slate-800 to-slate-900 text-white font-black text-base flex items-center justify-center shadow-xs shrink-0">
                          {parsedName.charAt(0).toUpperCase()}
                        </div>

                        <div>
                          <h4 className="font-extrabold text-slate-900 text-base tracking-tight">
                            {parsedName}
                          </h4>
                          <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 mt-0.5">
                            <MapPin className="w-3.5 h-3.5 text-orange-500 shrink-0" />
                            <span className="text-slate-700 font-bold">{parsedArea}</span>
                            <span className="text-slate-300">•</span>
                            <span className="text-slate-400">{currentReview.createdAt}</span>
                          </div>
                        </div>
                      </div>

                      {/* Manual Previous & Next buttons */}
                      <div className="flex items-center gap-2 self-end sm:self-center">
                        <button
                          onClick={handlePrev}
                          className="p-2.5 rounded-xl bg-slate-100 hover:bg-orange-500 hover:text-white text-slate-700 transition-all cursor-pointer shadow-xs active:scale-95"
                          title="Previous Review"
                          aria-label="Previous Review"
                        >
                          <ChevronLeft className="w-5 h-5" />
                        </button>
                        <button
                          onClick={handleNext}
                          className="p-2.5 rounded-xl bg-slate-100 hover:bg-orange-500 hover:text-white text-slate-700 transition-all cursor-pointer shadow-xs active:scale-95"
                          title="Next Review"
                          aria-label="Next Review"
                        >
                          <ChevronRight className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                  </motion.div>
                </AnimatePresence>
              </div>
            );
          })()
        )}

        {/* 1-by-1 Pagination Pills */}
        {reviews.length > 1 && (
          <div className="mt-5 flex flex-col sm:flex-row items-center justify-between gap-3 px-1">
            <div className="flex items-center gap-1.5">
              {reviews.map((_, idx) => (
                <button
                  key={idx}
                  onClick={() => scrollToReview(idx)}
                  className={`h-2.5 rounded-full transition-all duration-300 cursor-pointer ${
                    idx === activeReviewIndex
                      ? "w-8 bg-orange-500"
                      : "w-2.5 bg-slate-300 hover:bg-slate-400"
                  }`}
                  title={`View Review ${idx + 1}`}
                  aria-label={`View Review ${idx + 1}`}
                />
              ))}
            </div>

            <div className="text-xs text-slate-500 font-medium">
              Auto-scrolling 1 by 1 every 4 sec <span className="text-slate-400">(hover/touch to pause)</span>
            </div>
          </div>
        )}
      </div>

      {/* ========================================================================= */}
      {/* WRITE A REVIEW MODAL */}
      {/* ========================================================================= */}
      {isWriteModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4 animate-in fade-in duration-200">
          <div className="relative w-full max-w-lg bg-white rounded-3xl p-6 sm:p-8 shadow-2xl border border-slate-200 overflow-hidden max-h-[90vh] overflow-y-auto">
            {/* Modal Header */}
            <div className="flex items-start justify-between gap-4 mb-5 pb-4 border-b border-slate-100">
              <div>
                <h4 className="text-xl font-black font-display text-slate-900 tracking-tight">
                  Write a Customer Review
                </h4>
                <p className="text-xs text-slate-500 mt-0.5">
                  Sharing review for <strong className="text-slate-800">{productName}</strong>
                </p>
              </div>

              <button
                onClick={() => setIsWriteModalOpen(false)}
                className="p-1.5 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-colors cursor-pointer"
                aria-label="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {formError && (
              <div className="mb-4 p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-bold">
                {formError}
              </div>
            )}

            <form onSubmit={handleSubmitReview} className="space-y-4 text-left">
              {/* Rating Selector */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Overall Rating *
                </label>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-1 text-amber-400">
                    {[1, 2, 3, 4, 5].map((starVal) => {
                      const isFilled =
                        hoverRating !== null
                          ? starVal <= hoverRating
                          : starVal <= selectedRating;
                      return (
                        <button
                          key={starVal}
                          type="button"
                          onMouseEnter={() => setHoverRating(starVal)}
                          onMouseLeave={() => setHoverRating(null)}
                          onClick={() => setSelectedRating(starVal)}
                          className="p-1 transition-transform hover:scale-110 active:scale-95 cursor-pointer"
                        >
                          <Star
                            className={`w-7 h-7 ${
                              isFilled
                                ? "fill-amber-400 text-amber-400"
                                : "text-slate-200"
                            }`}
                          />
                        </button>
                      );
                    })}
                  </div>
                  <span className="text-xs font-bold text-slate-600 ml-2">
                    {ratingLabels[hoverRating || selectedRating] || "Select"}
                  </span>
                </div>
              </div>

              {/* Reviewer Name */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Name *
                </label>
                <input
                  type="text"
                  value={reviewerName}
                  onChange={(e) => setReviewerName(e.target.value)}
                  placeholder="e.g. Rameshwar Singh"
                  required
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm font-medium text-slate-900 focus:outline-hidden focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all"
                />
              </div>

              {/* Reviewer Area Selection */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Area / City *
                </label>
                <select
                  value={reviewerArea}
                  onChange={(e) => setReviewerArea(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm font-medium text-slate-900 focus:outline-hidden focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all bg-white"
                >
                  {allowedAreas.map((a) => (
                    <option key={a} value={a}>
                      {a}
                    </option>
                  ))}
                </select>
              </div>

              {/* Review Content */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Experience / Review *
                </label>
                <textarea
                  value={reviewContent}
                  onChange={(e) => setReviewContent(e.target.value)}
                  rows={4}
                  placeholder="Share details about material thickness, waterproofing, usage in curing/shelter, store service, etc."
                  required
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm font-medium text-slate-900 focus:outline-hidden focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all resize-none"
                />
              </div>

              {/* Submit Buttons */}
              <div className="pt-3 flex items-center justify-end gap-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsWriteModalOpen(false)}
                  className="px-5 py-2.5 rounded-xl border border-slate-200 text-slate-600 font-bold text-xs hover:bg-slate-50 transition-colors cursor-pointer"
                >
                  Cancel
                </button>

                <button
                  type="submit"
                  disabled={submitting}
                  className="px-6 py-2.5 rounded-xl bg-orange-500 hover:bg-orange-600 active:scale-95 text-white font-extrabold text-xs shadow-md transition-all cursor-pointer disabled:opacity-50"
                >
                  {submitting ? "Submitting..." : "Submit Review"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
