import React, { useState, useEffect, useRef } from "react";
import {
  Star,
  MessageSquarePlus,
  CheckCircle2,
  X,
  ChevronLeft,
  ChevronRight,
  MapPin,
  Calendar,
  Sparkles,
  Quote,
} from "lucide-react";
import { ProductReview } from "../../types/productDetails";
import {
  getReviewsForProduct,
  addReviewForProduct,
  computeRatingStats,
  getAutoGeneratedReviews,
  RatingStats,
} from "../../lib/reviewsStorage";

interface ProductReviewsSectionProps {
  productId: string;
  productName: string;
  onStatsChange?: (stats: RatingStats) => void;
}

function parseCustomerNameAndArea(fullName: string): { name: string; area: string } {
  const match = fullName.match(/^(.*?)\s*\((.*?)\)$/);
  if (match) {
    return { name: match[1].trim(), area: match[2].trim() };
  }
  return { name: fullName, area: "Maharajganj" };
}

export default function ProductReviewsSection({
  productId,
  productName,
  onStatsChange,
}: ProductReviewsSectionProps) {
  const [reviews, setReviews] = useState<ProductReview[]>(() =>
    getAutoGeneratedReviews(productId)
  );
  const [loading, setLoading] = useState(false);
  const [isWriteModalOpen, setIsWriteModalOpen] = useState(false);
  const [activeCoachIndex, setActiveCoachIndex] = useState(0);

  const trainTrackRef = useRef<HTMLDivElement>(null);

  // Form State
  const [reviewerName, setReviewerName] = useState("");
  const [reviewerArea, setReviewerArea] = useState("Maharajganj");
  const [selectedRating, setSelectedRating] = useState<number>(5);
  const [hoverRating, setHoverRating] = useState<number | null>(null);
  const [reviewContent, setReviewContent] = useState("");
  const [formError, setFormError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Load reviews whenever productId changes
  useEffect(() => {
    let isMounted = true;
    setLoading(true);

    getReviewsForProduct(productId).then((data) => {
      if (isMounted) {
        const top10 = data.slice(0, 10);
        setReviews(top10);
        setLoading(false);
        const stats = computeRatingStats(top10);
        if (onStatsChange) {
          onStatsChange(stats);
        }
      }
    });

    return () => {
      isMounted = false;
    };
  }, [productId]);

  // Track active coach while user scrolls
  const handleScroll = () => {
    if (!trainTrackRef.current) return;
    const container = trainTrackRef.current;
    const cardWidth = container.firstElementChild?.clientWidth || 340;
    const scrollLeft = container.scrollLeft;
    const index = Math.round(scrollLeft / (cardWidth + 16));
    setActiveCoachIndex(Math.max(0, Math.min(reviews.length - 1, index)));
  };

  const scrollToCoach = (index: number) => {
    if (!trainTrackRef.current) return;
    const container = trainTrackRef.current;
    const cardWidth = container.firstElementChild?.clientWidth || 340;
    container.scrollTo({
      left: index * (cardWidth + 16),
      behavior: "smooth",
    });
    setActiveCoachIndex(index);
  };

  const scrollPrev = () => {
    scrollToCoach(Math.max(0, activeCoachIndex - 1));
  };

  const scrollNext = () => {
    scrollToCoach(Math.min(reviews.length - 1, activeCoachIndex + 1));
  };

  const stats = computeRatingStats(reviews);

  const handleSubmitReview = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError("");

    if (!reviewerName.trim()) {
      setFormError("Please enter your name.");
      return;
    }
    if (!selectedRating || selectedRating < 1 || selectedRating > 5) {
      setFormError("Please select a rating between 1 and 5 stars.");
      return;
    }
    if (!reviewContent.trim()) {
      setFormError("Please write a few words about your experience with this product.");
      return;
    }

    setSubmitting(true);
    try {
      const formattedNameWithArea = `${reviewerName.trim()} (${reviewerArea})`;
      const created = await addReviewForProduct(productId, {
        customerName: formattedNameWithArea,
        rating: selectedRating,
        reviewText: reviewContent,
      });

      const updatedReviews = [created, ...reviews.filter((r) => r.id !== created.id)].slice(0, 10);
      setReviews(updatedReviews);
      const updatedStats = computeRatingStats(updatedReviews);
      if (onStatsChange) {
        onStatsChange(updatedStats);
      }

      // Reset form and close modal
      setReviewerName("");
      setSelectedRating(5);
      setReviewContent("");
      setIsWriteModalOpen(false);
      scrollToCoach(0);
    } catch (err) {
      setFormError("Failed to save your review. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  const ratingLabels: Record<number, string> = {
    1: "Poor",
    2: "Fair",
    3: "Good",
    4: "Very Good",
    5: "Excellent",
  };

  const allowedAreas = [
    "Maharajganj",
    "Basantpur",
    "Ekma",
    "Chhapra",
    "Patna",
    "Siwan",
    "Gopalganj",
  ];

  return (
    <div
      id="customer-reviews"
      className="w-full scroll-mt-28 mt-12 pt-8 border-t border-slate-200"
    >
      {/* Header & Write Review Action */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-black text-orange-600 uppercase tracking-widest bg-orange-50 border border-orange-200/70 px-2.5 py-0.5 rounded-md">
              10 VERIFIED RATINGS
            </span>
            <span className="text-xs font-semibold text-slate-400">
              • Regional Express Feed
            </span>
          </div>
          <h3 className="text-2xl sm:text-3xl font-black font-display text-slate-900 tracking-tight">
            Customer Reviews ({stats.average.toFixed(1)} ★)
          </h3>
          <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
            Verified buyer feedback from Maharajganj, Basantpur, Ekma, Chhapra, Patna, Siwan & Gopalganj.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          {/* Train Navigation Buttons */}
          <div className="flex items-center gap-1.5 bg-slate-100 p-1 rounded-xl border border-slate-200/80">
            <button
              onClick={scrollPrev}
              disabled={activeCoachIndex === 0}
              className="p-2 rounded-lg bg-white shadow-xs hover:bg-orange-500 hover:text-white text-slate-700 disabled:opacity-30 disabled:hover:bg-white disabled:hover:text-slate-700 transition-all cursor-pointer"
              title="Previous Review (Coach)"
              aria-label="Previous Review"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <span className="text-xs font-mono font-bold px-2 text-slate-700">
              {activeCoachIndex + 1} / {reviews.length}
            </span>
            <button
              onClick={scrollNext}
              disabled={activeCoachIndex >= reviews.length - 1}
              className="p-2 rounded-lg bg-white shadow-xs hover:bg-orange-500 hover:text-white text-slate-700 disabled:opacity-30 disabled:hover:bg-white disabled:hover:text-slate-700 transition-all cursor-pointer"
              title="Next Review (Coach)"
              aria-label="Next Review"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>

          <button
            onClick={() => {
              setFormError("");
              setIsWriteModalOpen(true);
            }}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-orange-600 text-white font-extrabold text-xs sm:text-sm shadow-sm transition-all duration-200 cursor-pointer active:scale-95"
          >
            <MessageSquarePlus className="w-4 h-4" />
            <span className="hidden sm:inline">Write a Review</span>
            <span className="sm:hidden">Review</span>
          </button>
        </div>
      </div>

      {/* Rating Score Summary Card */}
      <div className="bg-white rounded-3xl p-5 sm:p-6 border border-slate-200/80 shadow-xs mb-6 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="flex items-baseline gap-1">
            <span className="text-4xl sm:text-5xl font-black font-display text-slate-900 tracking-tight">
              {stats.average.toFixed(1)}
            </span>
            <span className="text-slate-400 text-base font-bold">/ 5</span>
          </div>

          <div className="flex flex-col">
            <div className="flex items-center gap-1 text-amber-400">
              {[1, 2, 3, 4, 5].map((s) => (
                <Star
                  key={s}
                  className={`w-4 h-4 ${
                    s <= Math.round(stats.average)
                      ? "fill-amber-400 text-amber-400"
                      : "text-slate-200"
                  }`}
                />
              ))}
            </div>
            <span className="text-xs font-semibold text-slate-600 mt-0.5">
              10 Verified Ratings (100% Genuine)
            </span>
          </div>
        </div>

        {/* Region Badges Pills */}
        <div className="flex flex-wrap items-center justify-center sm:justify-end gap-1.5 text-[11px] font-semibold text-slate-600">
          <span className="text-slate-400 text-xs mr-1 hidden md:inline">Verified Areas:</span>
          {allowedAreas.map((area) => (
            <span
              key={area}
              className="bg-slate-100 hover:bg-orange-50 border border-slate-200/70 text-slate-700 px-2 py-0.5 rounded-md text-[10px] font-bold"
            >
              {area}
            </span>
          ))}
        </div>
      </div>

      {/* ========================================================================= */}
      {/* HORIZONTAL REVIEWS TRAIN (COACH-BY-COACH SIDE BY SIDE) */}
      {/* ========================================================================= */}
      <div className="relative w-full">
        {/* Train Coaches Scroll Track */}
        <div
          ref={trainTrackRef}
          onScroll={handleScroll}
          className="flex gap-4 sm:gap-5 overflow-x-auto pb-4 pt-1 snap-x snap-mandatory scroll-smooth scrollbar-none"
          style={{ scrollbarWidth: "none", msOverflowStyle: "none" }}
        >
          {loading ? (
            <div className="w-full text-center py-12 text-slate-400 text-sm font-medium">
              Loading reviews train...
            </div>
          ) : (
            reviews.map((rev, index) => {
              const { name: parsedName, area: parsedArea } = parseCustomerNameAndArea(
                rev.customerName
              );
              const isActive = index === activeCoachIndex;

              return (
                <div
                  key={rev.id || index}
                  onClick={() => scrollToCoach(index)}
                  className={`min-w-[290px] max-w-[320px] sm:min-w-[340px] sm:max-w-[360px] md:min-w-[370px] md:max-w-[390px] shrink-0 snap-center rounded-3xl p-5 sm:p-6 border transition-all duration-300 flex flex-col justify-between cursor-pointer ${
                    isActive
                      ? "bg-white border-orange-300 shadow-md ring-2 ring-orange-500/20 scale-[1.01]"
                      : "bg-white/90 border-slate-200/80 shadow-xs hover:border-slate-300 hover:bg-white hover:shadow-sm"
                  }`}
                >
                  <div>
                    {/* Coach Number & Rating Row */}
                    <div className="flex items-center justify-between gap-2 mb-3 pb-3 border-b border-slate-100">
                      <div className="flex items-center gap-1.5">
                        <span className="text-[10px] font-black tracking-wider uppercase bg-orange-100 text-orange-800 px-2 py-0.5 rounded-md flex items-center gap-1">
                          Coach #{index + 1}
                        </span>
                        <span className="text-[11px] font-bold text-slate-400">
                          of 10
                        </span>
                      </div>

                      <div className="flex items-center gap-1 bg-amber-50 px-2 py-0.5 rounded-md border border-amber-200/60">
                        <div className="flex items-center text-amber-400">
                          {[1, 2, 3, 4, 5].map((s) => (
                            <Star
                              key={s}
                              className={`w-3.5 h-3.5 ${
                                s <= rev.rating
                                  ? "fill-amber-400 text-amber-400"
                                  : "text-slate-200"
                              }`}
                            />
                          ))}
                        </div>
                        <span className="text-xs font-black text-amber-900 font-mono ml-0.5">
                          {rev.rating}.0
                        </span>
                      </div>
                    </div>

                    {/* Customer Info & Location */}
                    <div className="flex items-center gap-3 mb-3">
                      <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-slate-800 to-slate-900 text-white font-black text-sm flex items-center justify-center shadow-xs shrink-0">
                        {parsedName.charAt(0).toUpperCase()}
                      </div>

                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-1.5 flex-wrap">
                          <h4 className="font-extrabold text-slate-900 text-sm tracking-tight truncate">
                            {parsedName}
                          </h4>
                          <span className="inline-flex items-center gap-0.5 text-[10px] font-bold text-emerald-700 bg-emerald-50 px-1.5 py-0.2 rounded border border-emerald-200/60 shrink-0">
                            <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                            Verified
                          </span>
                        </div>

                        {/* Location Tag */}
                        <div className="flex items-center gap-1 text-[11px] font-semibold text-slate-500 mt-0.5">
                          <MapPin className="w-3 h-3 text-orange-500 shrink-0" />
                          <span className="text-slate-700 font-bold">{parsedArea}</span>
                          <span className="text-slate-300">•</span>
                          <span className="text-slate-400 text-[10px]">{rev.createdAt}</span>
                        </div>
                      </div>
                    </div>

                    {/* Review Text */}
                    <div className="relative mt-2 text-slate-700 text-xs sm:text-sm leading-relaxed font-normal bg-slate-50/70 p-3.5 rounded-2xl border border-slate-100">
                      <Quote className="w-4 h-4 text-orange-400/50 mb-1" />
                      <p className="italic">"{rev.reviewText}"</p>
                    </div>
                  </div>

                  {/* Coach Bottom Bar */}
                  <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-[10px] text-slate-400 font-medium">
                    <span className="flex items-center gap-1 text-slate-500 font-semibold">
                      <Sparkles className="w-3 h-3 text-amber-500" />
                      Verified Store Purchase
                    </span>
                    <span className="font-mono font-bold text-orange-600">
                      Om Shringar Client
                    </span>
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Train Track Visual Representation & Station Dots */}
        <div className="mt-4 pt-2 flex flex-col items-center">
          {/* Track Railway Line with 10 Dots */}
          <div className="w-full max-w-md flex items-center justify-between relative px-2 py-2">
            <div className="absolute inset-x-4 top-1/2 -translate-y-1/2 h-1 bg-slate-200 rounded-full z-0" />
            <div
              className="absolute left-4 top-1/2 -translate-y-1/2 h-1 bg-orange-500 rounded-full transition-all duration-300 z-0"
              style={{
                width: `${(activeCoachIndex / Math.max(1, reviews.length - 1)) * 92}%`,
              }}
            />

            {reviews.map((_, dotIdx) => (
              <button
                key={dotIdx}
                onClick={() => scrollToCoach(dotIdx)}
                className={`relative z-10 w-6 h-6 rounded-full flex items-center justify-center font-mono text-[10px] font-bold transition-all cursor-pointer ${
                  dotIdx === activeCoachIndex
                    ? "bg-orange-500 text-white shadow-md scale-110"
                    : dotIdx < activeCoachIndex
                    ? "bg-orange-200 text-orange-900"
                    : "bg-white text-slate-400 border border-slate-300 hover:border-orange-400"
                }`}
                title={`Jump to Review #${dotIdx + 1}`}
                aria-label={`Jump to Review ${dotIdx + 1}`}
              >
                {dotIdx + 1}
              </button>
            ))}
          </div>

          <div className="flex items-center justify-between w-full text-xs text-slate-400 font-medium mt-2 px-1">
            <span>‹ Swipe left/right to browse all 10 reviews ›</span>
            <span className="font-bold text-slate-600">
              Showing Coach #{activeCoachIndex + 1} of 10
            </span>
          </div>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* WRITE A REVIEW MODAL */}
      {/* ========================================================================= */}
      {isWriteModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4 animate-in fade-in duration-200">
          <div className="relative w-full max-w-lg bg-white rounded-3xl p-6 sm:p-8 shadow-2xl border border-slate-200 overflow-hidden max-h-[90vh] overflow-y-auto">
            {/* Modal Header */}
            <div className="flex items-start justify-between gap-4 mb-5 pb-4 border-b border-slate-100">
              <div>
                <h4 className="text-xl font-black font-display text-slate-900 tracking-tight">
                  Write a Customer Review
                </h4>
                <p className="text-xs text-slate-500 mt-0.5">
                  Sharing review for <strong className="text-slate-800">{productName}</strong>
                </p>
              </div>

              <button
                onClick={() => setIsWriteModalOpen(false)}
                className="p-1.5 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-colors cursor-pointer"
                aria-label="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {formError && (
              <div className="mb-4 p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-bold">
                {formError}
              </div>
            )}

            <form onSubmit={handleSubmitReview} className="space-y-4 text-left">
              {/* Rating Selector */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Overall Rating *
                </label>
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-1 text-amber-400">
                    {[1, 2, 3, 4, 5].map((starVal) => {
                      const isFilled =
                        hoverRating !== null
                          ? starVal <= hoverRating
                          : starVal <= selectedRating;
                      return (
                        <button
                          key={starVal}
                          type="button"
                          onMouseEnter={() => setHoverRating(starVal)}
                          onMouseLeave={() => setHoverRating(null)}
                          onClick={() => setSelectedRating(starVal)}
                          className="p-1 transition-transform hover:scale-110 active:scale-95 cursor-pointer"
                        >
                          <Star
                            className={`w-7 h-7 ${
                              isFilled
                                ? "fill-amber-400 text-amber-400"
                                : "text-slate-200"
                            }`}
                          />
                        </button>
                      );
                    })}
                  </div>
                  <span className="text-xs font-bold text-slate-600 ml-2">
                    {ratingLabels[hoverRating || selectedRating] || "Select"}
                  </span>
                </div>
              </div>

              {/* Reviewer Name */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Name *
                </label>
                <input
                  type="text"
                  value={reviewerName}
                  onChange={(e) => setReviewerName(e.target.value)}
                  placeholder="e.g. Rameshwar Singh"
                  required
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm font-medium text-slate-900 focus:outline-hidden focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all"
                />
              </div>

              {/* Reviewer Area Selection */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Area / City *
                </label>
                <select
                  value={reviewerArea}
                  onChange={(e) => setReviewerArea(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm font-medium text-slate-900 focus:outline-hidden focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all bg-white"
                >
                  {allowedAreas.map((a) => (
                    <option key={a} value={a}>
                      {a}
                    </option>
                  ))}
                </select>
              </div>

              {/* Review Content */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1.5">
                  Your Experience / Review *
                </label>
                <textarea
                  value={reviewContent}
                  onChange={(e) => setReviewContent(e.target.value)}
                  rows={4}
                  placeholder="Share details about material thickness, waterproofing, usage in curing/shelter, store service, etc."
                  required
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm font-medium text-slate-900 focus:outline-hidden focus:border-orange-500 focus:ring-2 focus:ring-orange-200 transition-all resize-none"
                />
              </div>

              {/* Submit Buttons */}
              <div className="pt-3 flex items-center justify-end gap-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsWriteModalOpen(false)}
                  className="px-5 py-2.5 rounded-xl border border-slate-200 text-slate-600 font-bold text-xs hover:bg-slate-50 transition-colors cursor-pointer"
                >
                  Cancel
                </button>

                <button
                  type="submit"
                  disabled={submitting}
                  className="px-6 py-2.5 rounded-xl bg-orange-500 hover:bg-orange-600 active:scale-95 text-white font-extrabold text-xs shadow-md transition-all cursor-pointer disabled:opacity-50"
                >
                  {submitting ? "Submitting..." : "Submit Review"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
