import { useState, useEffect, MouseEvent } from "react";
import { motion, AnimatePresence } from "motion/react";
import { ChevronLeft, ChevronRight, Star, Factory, ShoppingBag } from "lucide-react";
import { Product } from "../data";
import LazyImage from "./LazyImage";
import { getAutoGeneratedReviews, computeRatingStats } from "../lib/reviewsStorage";

interface ProductCardProps {
  product: Product;
  onEnquire: (productName: string) => void;
  onViewDetails: (product: Product) => void;
  currentLanguage?: "en" | "hi";
}

export default function ProductCard({ product, onViewDetails, currentLanguage = "en" }: ProductCardProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isHovered, setIsHovered] = useState(false);

  // Dynamic rating stats for this product (4.8 or 4.9)
  const stats = computeRatingStats(getAutoGeneratedReviews(product.id));

  useEffect(() => {
    if (product.images.length <= 1 || isHovered) return;

    const interval = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % product.images.length);
    }, 4000);

    return () => clearInterval(interval);
  }, [product.images.length, isHovered]);

  const nextSlide = (e: MouseEvent) => {
    e.stopPropagation();
    setCurrentSlide((prev) => (prev + 1) % product.images.length);
  };

  const prevSlide = (e: MouseEvent) => {
    e.stopPropagation();
    setCurrentSlide((prev) => (prev - 1 + product.images.length) % product.images.length);
  };

  const isPolyware = product.division === "polyware";

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      transition={{ duration: 0.6 }}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onClick={() => onViewDetails(product)}
      className={`bg-white rounded-2xl sm:rounded-3xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 flex flex-col h-full group cursor-pointer border ${
        isPolyware 
          ? "border-slate-200/90 hover:border-orange-500/60" 
          : "border-slate-200/90 hover:border-indigo-400/60"
      }`}
    >
      {/* Image Carousel Area */}
      <div 
        onClick={(e) => {
          e.stopPropagation();
          onViewDetails(product);
        }}
        className="relative aspect-video w-full overflow-hidden bg-slate-900 cursor-pointer"
      >
        {/* Division Badge (Polyware vs General Store) */}
        <div className="absolute top-2 right-2 sm:top-3 sm:right-3 z-20 flex flex-col items-end gap-1">
          {isPolyware ? (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 sm:px-2.5 sm:py-1 rounded-full bg-[#0B2D5C]/90 text-orange-400 backdrop-blur-md border border-orange-500/30 text-[9px] sm:text-[10px] font-black uppercase tracking-wider shadow-sm">
              <Factory className="w-2.5 h-2.5 sm:w-3 sm:h-3 text-orange-400" />
              <span>POLYWARE</span>
            </span>
          ) : (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 sm:px-2.5 sm:py-1 rounded-full bg-slate-900/90 text-indigo-200 backdrop-blur-md border border-indigo-400/30 text-[9px] sm:text-[10px] font-black uppercase tracking-wider shadow-sm">
              <ShoppingBag className="w-2.5 h-2.5 sm:w-3 sm:h-3 text-indigo-300" />
              <span>GENERAL STORE</span>
            </span>
          )}

          {/* Special Retail Availability Badge (e.g. Tablecloth, Thermocol, Mat in Polyware) */}
          {product.saleType && (
            <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-emerald-600/95 text-white backdrop-blur-md text-[8px] sm:text-[9px] font-bold tracking-tight shadow-sm border border-emerald-400/30">
              <span>{product.saleType}</span>
            </span>
          )}
        </div>

        {/* Video Badge */}
        {product.video && (
          <div className="absolute top-2 left-2 sm:top-3 sm:left-3 z-20 flex items-center gap-1 sm:gap-1.5 px-2 py-0.5 sm:px-2.5 sm:py-1 rounded-full bg-black/65 backdrop-blur-md border border-white/20 text-white text-[9px] sm:text-[10px] font-black uppercase tracking-wider shadow-md">
            <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
            <span>Video Demo</span>
          </div>
        )}

        {/* Carousel Images */}
        <div className="absolute inset-0 w-full h-full">
          <AnimatePresence mode="wait">
            <motion.div
              key={currentSlide}
              initial={{ opacity: 0, scale: 1.05 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}
              className="w-full h-full cursor-pointer"
            >
              <LazyImage
                src={product.images[currentSlide]}
                alt={`${product.name} - View ${currentSlide + 1}`}
                referrerPolicy="no-referrer"
                className="group-hover:scale-105 transition-transform duration-700 cursor-pointer"
              />
            </motion.div>
          </AnimatePresence>
        </div>

        {/* Subtle Overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent z-10 pointer-events-none" />

        {/* Navigation Arrows */}
        {product.images.length > 1 && (
          <>
            <button
              onClick={prevSlide}
              aria-label="Previous Slide"
              className="absolute left-1.5 sm:left-3 top-1/2 -translate-y-1/2 z-20 w-6 h-6 sm:w-8 sm:h-8 flex items-center justify-center rounded-full bg-black/45 hover:bg-orange-500 text-white backdrop-blur-sm transition-all duration-200 active:scale-90 opacity-0 group-hover:opacity-100"
            >
              <ChevronLeft className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            </button>
            <button
              onClick={nextSlide}
              aria-label="Next Slide"
              className="absolute right-1.5 sm:right-3 top-1/2 -translate-y-1/2 z-20 w-6 h-6 sm:w-8 sm:h-8 flex items-center justify-center rounded-full bg-black/45 hover:bg-orange-500 text-white backdrop-blur-sm transition-all duration-200 active:scale-90 opacity-0 group-hover:opacity-100"
            >
              <ChevronRight className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            </button>

            {/* Slider Dots Indicator */}
            <div className="absolute bottom-2 sm:bottom-2.5 left-1/2 -translate-x-1/2 z-20 flex gap-1 sm:gap-1.5 bg-black/40 px-2 sm:px-2.5 py-0.5 sm:py-1 rounded-full backdrop-blur-sm">
              {product.images.map((_, idx) => (
                <button
                  key={idx}
                  onClick={(e) => {
                    e.stopPropagation();
                    setCurrentSlide(idx);
                  }}
                  className={`w-1.5 h-1.5 rounded-full transition-all duration-200 ${
                    idx === currentSlide ? "bg-orange-500 w-3" : "bg-white/60 hover:bg-white"
                  }`}
                  aria-label={`Go to slide ${idx + 1}`}
                />
              ))}
            </div>
          </>
        )}
      </div>

      {/* Product Information Body */}
      <div className="p-3 sm:p-5 flex-grow flex flex-col justify-center">
        <div 
          onClick={(e) => {
            e.stopPropagation();
            onViewDetails(product);
          }}
          className="my-auto py-1 sm:py-2 cursor-pointer"
        >
          <h3 className="text-xs sm:text-base md:text-xl font-extrabold font-display text-slate-900 tracking-tight text-center group-hover:text-orange-600 transition-colors line-clamp-2 cursor-pointer leading-snug">
            {product.name}
          </h3>

          {/* Star Rating & Review Count */}
          <div className="flex items-center justify-center gap-1 sm:gap-1.5 mt-1.5 sm:mt-2.5 cursor-pointer">
            <div className="flex items-center text-amber-400">
              {[1, 2, 3, 4, 5].map((s) => (
                <Star
                  key={s}
                  className={`w-3 h-3 sm:w-3.5 sm:h-3.5 ${
                    s <= Math.round(stats.average)
                      ? "fill-amber-400 text-amber-400"
                      : "text-slate-200"
                  }`}
                />
              ))}
            </div>
            <span className="text-[10.5px] sm:text-xs font-black text-slate-800">{stats.average.toFixed(1)}</span>
            <span className="text-[9.5px] sm:text-[11px] text-slate-400 font-medium">({stats.totalCount})</span>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
