import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  ArrowLeft,
  Store,
  Star,
  Check,
  CheckCircle2,
  ShieldCheck,
  Package,
  Layers,
  Sparkles,
  MapPin,
  Heart,
  MessageSquare,
  HelpCircle,
  FileText,
  Truck,
  Building,
  Award,
  ChevronRight,
  ChevronLeft,
  HardHat,
  Bird,
  Leaf,
  Waves,
  Warehouse,
  Factory,
  Share2,
  Play,
  RotateCw,
  Volume2,
  VolumeX,
  Video,
} from "lucide-react";
import { Product, PRODUCTS, getProductSlug, BUSINESS_INFO } from "../data";
import ProductGallery from "./gallery/ProductGallery";
import TypeformEnquiryModal from "./enquiry/TypeformEnquiryModal";
import ProductReviewsSection from "./reviews/ProductReviewsSection";
import {
  RatingStats,
  getAutoGeneratedReviews,
  computeRatingStats,
} from "../lib/reviewsStorage";

interface SingleProductSectionProps {
  product: Product;
  onBack: () => void;
  currentLanguage?: "en" | "hi";
  onEnquire?: (productName: string) => void;
}

const WISHLIST_STORAGE_KEY = "om_shringar_wishlist";

interface ProductVideoProps {
  video: {
    url: string;
    title?: string;
    defaultRotate?: number;
  };
  productName: string;
}

function ProductVideoShowcase({ video, productName }: ProductVideoProps) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [rotation, setRotation] = useState<number>(video.defaultRotate || 0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isMuted, setIsMuted] = useState(false);

  const handleRotate = () => {
    setRotation((prev) => (prev + 90) % 360);
  };

  const togglePlay = () => {
    if (!videoRef.current) return;
    if (videoRef.current.paused) {
      videoRef.current.play().then(() => setIsPlaying(true)).catch(() => {});
    } else {
      videoRef.current.pause();
      setIsPlaying(false);
    }
  };

  const toggleMute = () => {
    if (!videoRef.current) return;
    videoRef.current.muted = !videoRef.current.muted;
    setIsMuted(videoRef.current.muted);
  };

  return (
    <div className="bg-slate-900 rounded-3xl border border-slate-800 p-6 sm:p-8 shadow-xl mb-10 text-white overflow-hidden relative">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-red-500 animate-pulse" />
            <span className="text-[11px] font-black uppercase tracking-widest text-orange-400">
              OFFICIAL DEMONSTRATION VIDEO
            </span>
          </div>
          <h2 className="text-xl sm:text-2xl font-black font-display tracking-tight text-white">
            {video.title || `${productName} Quality & Strength Demonstration`}
          </h2>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleRotate}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-semibold text-white transition-colors border border-white/10 cursor-pointer"
            title="Rotate Video 90°"
          >
            <RotateCw className="w-3.5 h-3.5" />
            <span>Rotate {rotation > 0 ? `(${rotation}°)` : ""}</span>
          </button>
          <button
            onClick={toggleMute}
            className="flex items-center justify-center w-9 h-9 rounded-xl bg-white/10 hover:bg-white/20 text-white transition-colors border border-white/10 cursor-pointer"
            title={isMuted ? "Unmute" : "Mute"}
          >
            {isMuted ? <VolumeX className="w-4 h-4 text-rose-400" /> : <Volume2 className="w-4 h-4" />}
          </button>
        </div>
      </div>

      <div className="relative rounded-2xl overflow-hidden bg-black flex items-center justify-center min-h-[260px] sm:min-h-[420px] max-h-[560px]">
        <div
          className="w-full h-full flex items-center justify-center transition-transform duration-300"
          style={{ transform: `rotate(${rotation}deg)` }}
        >
          <video
            ref={videoRef}
            src={video.url}
            controls
            playsInline
            className="w-full max-h-[520px] object-contain rounded-xl"
            onPlay={() => setIsPlaying(true)}
            onPause={() => setIsPlaying(false)}
          />
        </div>
      </div>

      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-400 border-t border-white/10 pt-3">
        <span className="flex items-center gap-1.5">
          <ShieldCheck className="w-4 h-4 text-emerald-400" />
          Authentic On-Counter & Testing Footage
        </span>
        <span className="text-[11px] text-slate-400">
          Source: {video.url.replace("https://", "").replace("/", "")}
        </span>
      </div>
    </div>
  );
}

function MobileRelatedProductsCarousel({ products }: { products: Product[] }) {
  const [activeIndex, setActiveIndex] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  const touchStartX = useRef<number | null>(null);
  const touchStartY = useRef<number | null>(null);
  const pauseTimer = useRef<NodeJS.Timeout | null>(null);

  const navigateToProduct = (prodId: string) => {
    const slug = getProductSlug(prodId);
    window.history.pushState({}, "", `/products/${slug}`);
    window.dispatchEvent(new Event("popstate"));
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handlePrev = () => {
    setActiveIndex((prev) => (prev === 0 ? products.length - 1 : prev - 1));
  };

  const handleNext = () => {
    setActiveIndex((prev) => (prev === products.length - 1 ? 0 : prev + 1));
  };

  // Auto-scroll one by one every 3.2 seconds on mobile
  useEffect(() => {
    if (isPaused || products.length <= 1) return;
    const interval = setInterval(() => {
      handleNext();
    }, 3200);
    return () => clearInterval(interval);
  }, [isPaused, activeIndex, products.length]);

  const pauseAutoScrollTemporarily = () => {
    setIsPaused(true);
    if (pauseTimer.current) clearTimeout(pauseTimer.current);
    pauseTimer.current = setTimeout(() => {
      setIsPaused(false);
    }, 4500);
  };

  const handleTouchStart = (e: React.TouchEvent) => {
    pauseAutoScrollTemporarily();
    touchStartX.current = e.touches[0].clientX;
    touchStartY.current = e.touches[0].clientY;
  };

  const handleTouchEnd = (e: React.TouchEvent) => {
    if (touchStartX.current !== null && touchStartY.current !== null) {
      const touchEndX = e.changedTouches[0].clientX;
      const touchEndY = e.changedTouches[0].clientY;
      const diffX = touchStartX.current - touchEndX;
      const diffY = touchStartY.current - touchEndY;
      const threshold = 35;

      if (Math.abs(diffX) > Math.abs(diffY) && Math.abs(diffX) > threshold) {
        if (diffX > 0) {
          handleNext();
        } else {
          handlePrev();
        }
      }
    }
    touchStartX.current = null;
    touchStartY.current = null;
  };

  if (!products || products.length === 0) return null;

  return (
    <div className="relative">
      {/* Mobile Header Controls: Counter & Manual Arrows */}
      <div className="flex items-center justify-between mb-3 px-1">
        <div className="flex items-center gap-1.5 text-xs text-slate-500 font-semibold">
          <span className="w-2 h-2 rounded-full bg-orange-500 animate-pulse" />
          <span>Auto-scrolling 1 by 1</span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-[11px] font-bold text-slate-600 bg-slate-100 px-2.5 py-0.5 rounded-full font-mono">
            {activeIndex + 1} / {products.length}
          </span>
          <button
            onClick={() => {
              pauseAutoScrollTemporarily();
              handlePrev();
            }}
            aria-label="Previous product"
            className="w-7 h-7 rounded-full bg-slate-100 active:bg-slate-200 border border-slate-200 flex items-center justify-center text-slate-700 transition-colors cursor-pointer"
          >
            <ChevronLeft className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => {
              pauseAutoScrollTemporarily();
              handleNext();
            }}
            aria-label="Next product"
            className="w-7 h-7 rounded-full bg-slate-100 active:bg-slate-200 border border-slate-200 flex items-center justify-center text-slate-700 transition-colors cursor-pointer"
          >
            <ChevronRight className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Slider Viewport */}
      <div
        className="overflow-hidden rounded-2xl border border-slate-200/90 shadow-sm bg-white"
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
      >
        <div
          className="flex transition-transform duration-500 ease-out"
          style={{ transform: `translateX(-${activeIndex * 100}%)` }}
        >
          {products.map((p) => {
            const pStats = computeRatingStats(getAutoGeneratedReviews(p.id));
            return (
              <div 
                key={p.id} 
                onClick={() => navigateToProduct(p.id)}
                className="w-full shrink-0 flex flex-col bg-white cursor-pointer"
              >
                <div 
                  onClick={(e) => {
                    e.stopPropagation();
                    navigateToProduct(p.id);
                  }}
                  className="relative aspect-[16/10] bg-slate-100 overflow-hidden cursor-pointer"
                >
                  <img
                    src={p.images[0]}
                    alt={p.name}
                    referrerPolicy="no-referrer"
                    className="w-full h-full object-cover cursor-pointer"
                    onClick={(e) => {
                      e.stopPropagation();
                      navigateToProduct(p.id);
                    }}
                  />
                  {p.isBestSeller && (
                    <span className="absolute top-2.5 left-2.5 bg-orange-500 text-white text-[10px] font-black px-2 py-0.5 rounded-md uppercase tracking-wider z-10 shadow-xs">
                      Best Seller
                    </span>
                  )}
                  <span className="absolute bottom-2.5 right-2.5 bg-black/60 backdrop-blur-xs text-white text-[10px] font-semibold px-2 py-0.5 rounded-full">
                    {p.category}
                  </span>
                </div>

                <div className="p-4 flex flex-col flex-1 justify-between">
                  <div
                    onClick={(e) => {
                      e.stopPropagation();
                      navigateToProduct(p.id);
                    }}
                    className="cursor-pointer"
                  >
                    <span className="text-[10px] font-bold text-orange-600 uppercase tracking-wider block mb-1">
                      {p.category}
                    </span>
                    <h4 
                      onClick={(e) => {
                        e.stopPropagation();
                        navigateToProduct(p.id);
                      }}
                      className="font-extrabold text-slate-900 text-base line-clamp-1 cursor-pointer hover:text-orange-600 transition-colors"
                    >
                      {p.name}
                    </h4>

                    {/* Ratings */}
                    <div className="flex items-center gap-1.5 mt-1.5 mb-1">
                      <div className="flex items-center text-amber-400">
                        {[1, 2, 3, 4, 5].map((s) => (
                          <Star
                            key={s}
                            className={`w-3.5 h-3.5 ${
                              s <= Math.round(pStats.average)
                                ? "fill-amber-400 text-amber-400"
                                : "text-slate-200"
                            }`}
                          />
                        ))}
                      </div>
                      <span className="text-xs font-bold text-slate-800">
                        {pStats.average.toFixed(1)}
                      </span>
                      <span className="text-[11px] text-slate-400">
                        ({pStats.totalCount} reviews)
                      </span>
                    </div>

                    <p className="text-xs text-slate-500 mt-1 line-clamp-2 leading-relaxed">
                      {p.description}
                    </p>
                  </div>

                  <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between gap-2">
                    <span
                      className={`text-xs font-bold px-2.5 py-1 rounded-md ${
                        p.id === "cosmetics-shringar"
                          ? "text-rose-700 bg-rose-50 border border-rose-200/60"
                          : "text-emerald-700 bg-emerald-50"
                      }`}
                    >
                      {p.id === "cosmetics-shringar"
                        ? "Retail Store Only"
                        : "Price on Enquiry"}
                    </span>
                    <a
                      href={`/products/${getProductSlug(p.id)}`}
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        navigateToProduct(p.id);
                      }}
                      className="text-xs font-bold text-orange-600 active:text-orange-700 flex items-center gap-1 py-1.5 px-3 rounded-lg bg-orange-50 border border-orange-200/60 cursor-pointer"
                    >
                      <span>View Product</span>
                      <ChevronRight className="w-3.5 h-3.5" />
                    </a>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Dots Indicator */}
      <div className="flex items-center justify-center gap-1.5 mt-3">
        {products.map((_, idx) => (
          <button
            key={idx}
            onClick={() => {
              pauseAutoScrollTemporarily();
              setActiveIndex(idx);
            }}
            aria-label={`Go to slide ${idx + 1}`}
            className={`transition-all duration-300 rounded-full cursor-pointer ${
              idx === activeIndex
                ? "w-6 h-1.5 bg-orange-500"
                : "w-1.5 h-1.5 bg-slate-300"
            }`}
          />
        ))}
      </div>
    </div>
  );
}

export default function SingleProductSection({
  product,
  onBack,
  currentLanguage = "en",
}: SingleProductSectionProps) {
  const [isEnquiryModalOpen, setIsEnquiryModalOpen] = useState(false);
  const [isInWishlist, setIsInWishlist] = useState(false);
  const [openFaqIdx, setOpenFaqIdx] = useState<number | null>(0);

  // Auto-generated 4.8 / 4.9 rating stats initialization
  const [ratingStats, setRatingStats] = useState<RatingStats>(() => {
    const seed = getAutoGeneratedReviews(product.id);
    return computeRatingStats(seed);
  });

  // Re-seed stats when product.id changes
  useEffect(() => {
    const seed = getAutoGeneratedReviews(product.id);
    setRatingStats(computeRatingStats(seed));
  }, [product.id]);

  // Dynamic SEO Tags and Product Schema (JSON-LD)
  useEffect(() => {
    const isHi = currentLanguage === "hi";
    const titleSuffix = isHi
      ? " - ओम श्रृंगार तिरपाल स्टोर महाराजगंज"
      : " - Om Shringar Tirpal Store Maharajganj";
    document.title = `${product.name}${titleSuffix}`;

    const setMetaTag = (
      propertyOrName: string,
      content: string,
      isProperty = false
    ) => {
      const attribute = isProperty ? "property" : "name";
      let element = document.querySelector(`meta[${attribute}="${propertyOrName}"]`);
      if (!element) {
        element = document.createElement("meta");
        element.setAttribute(attribute, propertyOrName);
        document.head.appendChild(element);
      }
      element.setAttribute("content", content);
    };

    setMetaTag("description", product.description);
    const pageUrl = `${window.location.origin}/products/${getProductSlug(
      product.id
    )}`;
    setMetaTag("og:title", `${product.name}${titleSuffix}`, true);
    setMetaTag("og:description", product.description, true);
    setMetaTag("og:url", pageUrl, true);
    setMetaTag("og:type", "product", true);
    if (product.images && product.images[0]) {
      setMetaTag("og:image", product.images[0], true);
    }
  }, [product, currentLanguage]);

  // Check wishlist state
  useEffect(() => {
    try {
      const raw = localStorage.getItem(WISHLIST_STORAGE_KEY);
      if (raw) {
        const list: string[] = JSON.parse(raw);
        setIsInWishlist(list.includes(product.id));
      }
    } catch {
      // ignore
    }
  }, [product.id]);

  const toggleWishlist = () => {
    try {
      const raw = localStorage.getItem(WISHLIST_STORAGE_KEY);
      let list: string[] = raw ? JSON.parse(raw) : [];
      if (list.includes(product.id)) {
        list = list.filter((id) => id !== product.id);
        setIsInWishlist(false);
      } else {
        list.push(product.id);
        setIsInWishlist(true);
      }
      localStorage.setItem(WISHLIST_STORAGE_KEY, JSON.stringify(list));
    } catch {
      setIsInWishlist(!isInWishlist);
    }
  };

  const scrollToReviews = () => {
    const el = document.getElementById("customer-reviews");
    if (el) {
      el.scrollIntoView({ behavior: "smooth" });
    }
  };

  // Related products from same category or catalog
  const sameCategoryProducts = PRODUCTS.filter(
    (p) => p.category === product.category && p.id !== product.id
  );
  const otherProducts = PRODUCTS.filter(
    (p) => p.category !== product.category && p.id !== product.id
  );
  const relatedProducts = [...sameCategoryProducts, ...otherProducts].slice(0, 6);

  const isRetailItem = product.category.toLowerCase().includes("retail");
  const isCosmetics =
    product.id === "cosmetics-shringar" ||
    product.id.toLowerCase().includes("cosmetic") ||
    product.name.toLowerCase().includes("cosmetic") ||
    product.name.toLowerCase().includes("shringar");

  // Helper to render application icons
  const getAppIcon = (app: string) => {
    const lower = app.toLowerCase();
    if (
      lower.includes("agri") ||
      lower.includes("farm") ||
      lower.includes("crop")
    )
      return <Leaf className="w-5 h-5 text-emerald-600" />;
    if (lower.includes("construction") || lower.includes("building"))
      return <HardHat className="w-5 h-5 text-amber-600" />;
    if (lower.includes("poultry") || lower.includes("bird"))
      return <Bird className="w-5 h-5 text-indigo-600" />;
    if (lower.includes("fish") || lower.includes("pond"))
      return <Waves className="w-5 h-5 text-blue-600" />;
    if (lower.includes("warehouse") || lower.includes("storage"))
      return <Warehouse className="w-5 h-5 text-orange-600" />;
    if (lower.includes("transport") || lower.includes("truck"))
      return <Truck className="w-5 h-5 text-cyan-600" />;
    if (lower.includes("industrial") || lower.includes("factory"))
      return <Factory className="w-5 h-5 text-slate-600" />;
    return <CheckCircle2 className="w-5 h-5 text-blue-500" />;
  };

  return (
    <div className="w-full bg-[#f8fafc] min-h-screen py-6 sm:py-10 text-slate-800 antialiased selection:bg-orange-100 selection:text-orange-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Amazon-Inspired Breadcrumbs */}
        <nav
          aria-label="Breadcrumb"
          className="mb-4 flex items-center gap-1.5 text-xs font-semibold text-slate-500 overflow-x-auto whitespace-nowrap py-1 scrollbar-none"
        >
          <a
            href="/"
            onClick={(e) => {
              e.preventDefault();
              onBack();
            }}
            className="hover:text-orange-600 transition-colors flex items-center gap-1"
          >
            <span>Home</span>
          </a>
          <span className="text-slate-300 font-normal">›</span>
          <span className="text-slate-500 hover:text-slate-800 transition-colors">
            {product.category}
          </span>
          <span className="text-slate-300 font-normal">›</span>
          <span className="text-slate-900 font-bold truncate max-w-[280px] sm:max-w-md">
            {product.name}
          </span>
        </nav>

        {/* Back / Navigation Bar */}
        <div className="mb-6 flex items-center justify-between gap-3 bg-white px-4 py-3 rounded-2xl border border-slate-200/80 shadow-xs">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-slate-700 hover:text-orange-600 font-bold text-xs sm:text-sm transition-colors py-1 px-2.5 rounded-lg hover:bg-slate-50 cursor-pointer group"
          >
            <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1 text-orange-600" />
            <span>Back to All Products</span>
          </button>

          <div className="flex items-center gap-2 text-xs font-semibold text-slate-500">
            <span className="hidden sm:inline">Category:</span>
            <span className="bg-orange-50 text-orange-700 border border-orange-200/60 font-bold px-2.5 py-0.5 rounded-full text-[11px]">
              {product.category}
            </span>
          </div>
        </div>

        {/* ========================================================================= */}
        {/* MAIN PRODUCT DETAIL GRID (Left 45% Gallery, Right 55% Product Info) */}
        {/* ========================================================================= */}
        <div className="bg-white rounded-3xl border border-slate-200/80 shadow-sm overflow-hidden mb-10">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 sm:gap-10 p-5 sm:p-8 lg:p-10">
            {/* LEFT COLUMN: Product Image Gallery & Video (45% desktop) */}
            <div className="lg:col-span-5 flex flex-col">
              <ProductGallery
                images={product.images}
                productName={product.name}
                isBestSeller={product.isBestSeller}
                video={product.video}
                videos={product.videos}
              />
            </div>

            {/* RIGHT COLUMN: Product Information Hierarchy (55% desktop) */}
            <div className="lg:col-span-7 flex flex-col justify-between">
              <div>
                {/* Category & Verified Badge */}
                <div className="flex flex-wrap items-center gap-2 mb-2.5">
                  <span className="text-[11px] font-black uppercase tracking-wider text-orange-600 bg-orange-50 border border-orange-100 px-2.5 py-0.5 rounded-md">
                    {product.division === "polyware" ? "POLYWARE INDUSTRIAL" : "GENERAL STORE RETAIL"}
                  </span>
                  <span className="text-slate-300">•</span>
                  <span className="text-[11px] font-bold text-slate-600 bg-slate-100 px-2.5 py-0.5 rounded-md">
                    {product.category}
                  </span>
                  {product.saleType && (
                    <>
                      <span className="text-slate-300">•</span>
                      <span className="text-[11px] font-extrabold text-emerald-700 bg-emerald-50 border border-emerald-200/60 px-2.5 py-0.5 rounded-md flex items-center gap-1">
                        <Check className="w-3 h-3 text-emerald-600" />
                        {product.saleType}
                      </span>
                    </>
                  )}
                  <span className="text-slate-300">•</span>
                  <span className="text-xs font-semibold text-slate-500 flex items-center gap-1">
                    <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" />
                    Genuine Stock
                  </span>
                </div>

                {/* Product Title */}
                <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black font-display text-slate-900 tracking-tight leading-tight mb-3">
                  {product.name}
                </h1>

                {/* Dynamic Rating & Review Count Link (4.8 or 4.9 average) */}
                <div className="flex items-center gap-3 mb-4 pb-4 border-b border-slate-100">
                  <div className="flex items-center gap-1 text-amber-400">
                    {[1, 2, 3, 4, 5].map((s) => (
                      <Star
                        key={s}
                        className={`w-4 h-4 ${
                          s <= Math.round(ratingStats.average || 4.8)
                            ? "fill-amber-400 text-amber-400"
                            : "text-slate-200"
                        }`}
                      />
                    ))}
                  </div>

                  <span className="text-xs sm:text-sm font-bold text-slate-800">
                    {ratingStats.average.toFixed(1)}
                  </span>

                  <span className="text-slate-300">•</span>

                  <button
                    onClick={scrollToReviews}
                    className="text-xs sm:text-sm font-semibold text-orange-600 hover:text-orange-700 hover:underline cursor-pointer"
                  >
                    {ratingStats.totalCount > 0
                      ? `${ratingStats.totalCount} Customer Reviews`
                      : "Verified Customer Reviews"}
                  </button>
                </div>

                {/* Badges Row */}
                <div className="flex flex-wrap gap-2 mb-5">
                  {isCosmetics ? (
                    <>
                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-rose-50 text-rose-800 border border-rose-200/70">
                        <Store className="w-3.5 h-3.5 text-rose-600" />
                        In-Store Retail Purchase Only
                      </span>

                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-pink-50 text-pink-800 border border-pink-200/70">
                        <Check className="w-3.5 h-3.5 text-pink-600" />
                        100% Genuine Branded Cosmetics
                      </span>

                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-purple-50 text-purple-800 border border-purple-200/70">
                        <ShieldCheck className="w-3.5 h-3.5 text-purple-600" />
                        Direct Walk-in Store Shopping
                      </span>
                    </>
                  ) : (
                    <>
                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-blue-50 text-blue-800 border border-blue-200/70">
                        <Package className="w-3.5 h-3.5 text-blue-600" />
                        {product.availableSizes
                          ? `Available in Multiple Sizes: ${product.availableSizes}`
                          : "Available in Multiple Sizes"}
                      </span>

                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-emerald-50 text-emerald-800 border border-emerald-200/70">
                        <Check className="w-3.5 h-3.5 text-emerald-600" />
                        {product.saleType
                          ? product.saleType
                          : isRetailItem
                          ? "Retail Counter Supply"
                          : "Wholesale & Retail Supply"}
                      </span>

                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-purple-50 text-purple-800 border border-purple-200/70">
                        <Layers className="w-3.5 h-3.5 text-purple-600" />
                        {product.saleType ? "Household, Commercial & Retail Use" : "Suitable for Industrial & Construction Use"}
                      </span>
                    </>
                  )}
                </div>

                {/* Short Professional Product Description */}
                <p className="text-slate-600 text-sm sm:text-base leading-relaxed mb-6 font-normal">
                  {product.description}
                </p>

                {/* Pricing Display */}
                {isCosmetics ? (
                  <div className="bg-rose-50/80 border border-rose-200/90 rounded-2xl p-4 sm:p-5 mb-6">
                    <div className="flex items-baseline gap-2 mb-1">
                      <span className="text-xs font-extrabold uppercase tracking-wider text-rose-700">
                        Purchasing Mode:
                      </span>
                      <span className="text-xl sm:text-2xl font-black text-rose-900 tracking-tight font-display">
                        Retail Walk-in Store Purchase Only
                      </span>
                    </div>
                    <p className="text-xs text-rose-800 font-medium">
                      Available exclusively for over-the-counter retail purchase at our Maharajganj store. No wholesale enquiries, bulk carton bookings, or online quote requests.
                    </p>
                  </div>
                ) : (
                  <div className="bg-slate-50 border border-slate-200/80 rounded-2xl p-4 sm:p-5 mb-6">
                    <div className="flex items-baseline gap-2 mb-1">
                      <span className="text-xs font-extrabold uppercase tracking-wider text-slate-500">
                        Pricing:
                      </span>
                      <span className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight font-display text-emerald-700">
                        Get Latest Price / Price on Enquiry
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 font-medium">
                      {product.saleType
                        ? "Retail counter purchase (single pieces) and bulk wholesale supplies available at our Maharajganj store."
                        : isRetailItem
                        ? "Direct retail shop pricing available based on current ready stock."
                        : "Wholesale & retail rates determined by dimensions, GSM thickness, and quantity."}
                    </p>
                  </div>
                )}

                {/* CTAs: Primary CTA & Secondary "Add to Wishlist" */}
                {isCosmetics ? (
                  <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 mb-6">
                    <div className="flex-1 flex items-center justify-center gap-2.5 px-6 py-4 rounded-2xl bg-rose-50 border border-rose-200 text-rose-800 font-black text-xs sm:text-sm tracking-wide">
                      <Store className="w-5 h-5 text-rose-600 shrink-0" />
                      <span>RETAIL WALK-IN ONLY (NO ONLINE ENQUIRY)</span>
                    </div>

                    <button
                      onClick={toggleWishlist}
                      className={`flex items-center justify-center gap-2 px-6 py-4 rounded-2xl border-2 font-bold text-xs sm:text-sm transition-all duration-200 cursor-pointer active:scale-95 ${
                        isInWishlist
                          ? "border-rose-500 bg-rose-50 text-rose-700"
                          : "border-slate-200 hover:border-slate-300 text-slate-700 hover:bg-slate-50"
                      }`}
                      title={
                        isInWishlist ? "Saved in your Wishlist" : "Save to Wishlist"
                      }
                    >
                      <Heart
                        className={`w-4 h-4 ${
                          isInWishlist
                            ? "fill-rose-500 text-rose-500"
                            : "text-slate-500"
                        }`}
                      />
                      <span>{isInWishlist ? "In Wishlist" : "Add to Wishlist"}</span>
                    </button>
                  </div>
                ) : (
                  <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 mb-6">
                    {/* Primary Prominent CTA */}
                    <button
                      onClick={() => setIsEnquiryModalOpen(true)}
                      className="flex-1 flex items-center justify-center gap-2.5 px-8 py-4 rounded-2xl bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600 active:scale-[0.98] text-white font-black text-sm sm:text-base tracking-wide shadow-lg shadow-orange-500/25 transition-all duration-200 cursor-pointer"
                    >
                      <MessageSquare className="w-5 h-5 fill-current" />
                      <span>ENQUIRE NOW</span>
                    </button>

                    {/* Secondary Wishlist CTA */}
                    <button
                      onClick={toggleWishlist}
                      className={`flex items-center justify-center gap-2 px-6 py-4 rounded-2xl border-2 font-bold text-xs sm:text-sm transition-all duration-200 cursor-pointer active:scale-95 ${
                        isInWishlist
                          ? "border-rose-500 bg-rose-50 text-rose-700"
                          : "border-slate-200 hover:border-slate-300 text-slate-700 hover:bg-slate-50"
                      }`}
                      title={
                        isInWishlist ? "Saved in your Wishlist" : "Save to Wishlist"
                      }
                    >
                      <Heart
                        className={`w-4 h-4 ${
                          isInWishlist
                            ? "fill-rose-500 text-rose-500"
                            : "text-slate-500"
                        }`}
                      />
                      <span>{isInWishlist ? "In Wishlist" : "Add to Wishlist"}</span>
                    </button>
                  </div>
                )}

                {/* Shipping & Physical Store Notice */}
                <div className="bg-amber-50/70 border border-amber-200/90 rounded-2xl p-4 mb-6 flex items-start gap-3 text-amber-950">
                  <Store className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
                  <div className="text-xs sm:text-sm font-medium leading-relaxed">
                    <strong className="text-amber-900 block font-bold text-xs uppercase tracking-wider mb-0.5">
                      Store Pickup & Visit Information:
                    </strong>
                    {isCosmetics
                      ? "Cosmetics and Bridal Shringar products are sold exclusively over-the-counter at our physical store in Maharajganj, Siwan, Bihar. Individual retail customers and walk-in families are welcome."
                      : isRetailItem
                      ? "This product is available for direct retail purchase at our physical store in Maharajganj, Siwan, Bihar."
                      : "For physical inspection and immediate pickup, visit our store & central warehouse in Maharajganj, Siwan, Bihar. Fast inquiries handled via WhatsApp."}
                  </div>
                </div>

                {/* Trust & Business Information Cards */}
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5 pt-2 border-t border-slate-100">
                  <div className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-50/80 border border-slate-150">
                    <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span className="text-[11px] font-bold text-slate-700">
                      Quality Checked Products
                    </span>
                  </div>

                  <div className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-50/80 border border-slate-150">
                    <Package className="w-4 h-4 text-orange-600 shrink-0" />
                    <span className="text-[11px] font-bold text-slate-700">
                      Wholesale & Retail Supply
                    </span>
                  </div>

                  <div className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-50/80 border border-slate-150">
                    <Layers className="w-4 h-4 text-blue-600 shrink-0" />
                    <span className="text-[11px] font-bold text-slate-700">
                      Multiple Sizes Available
                    </span>
                  </div>

                  <div className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-50/80 border border-slate-150">
                    <Building className="w-4 h-4 text-slate-700 shrink-0" />
                    <span className="text-[11px] font-bold text-slate-700">
                      Est. 2000 in Siwan, Bihar
                    </span>
                  </div>

                  <div className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-50/80 border border-slate-150">
                    <Award className="w-4 h-4 text-amber-600 shrink-0" />
                    <span className="text-[11px] font-bold text-slate-700">
                      Reliable Local Supplier
                    </span>
                  </div>

                  <div className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-50/80 border border-slate-150">
                    <MessageSquare className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span className="text-[11px] font-bold text-slate-700">
                      Fast Enquiry Response
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ========================================================================= */}
        {/* PRODUCT HIGHLIGHTS SECTION */}
        {/* ========================================================================= */}
        <div className="bg-white rounded-3xl border border-slate-200/80 p-6 sm:p-8 lg:p-10 shadow-sm mb-10">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-5 h-5 text-orange-500" />
            <span className="text-xs font-black text-slate-400 uppercase tracking-widest">
              CORE ADVANTAGES
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black font-display text-slate-900 tracking-tight mb-6">
            PRODUCT HIGHLIGHTS
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {product.features.map((feat, idx) => (
              <div
                key={idx}
                className="flex items-start gap-3 p-4 rounded-2xl bg-slate-50 border border-slate-150 hover:bg-orange-50/20 hover:border-orange-200 transition-colors"
              >
                <div className="w-7 h-7 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                  ✓
                </div>
                <div>
                  <p className="text-xs sm:text-sm font-bold text-slate-800 leading-snug">
                    {feat}
                  </p>
                </div>
              </div>
            ))}

            {/* Additional benefits from product data */}
            {product.benefits &&
              product.benefits.map((benefit, idx) => (
                <div
                  key={`b-${idx}`}
                  className="flex items-start gap-3 p-4 rounded-2xl bg-slate-50 border border-slate-150 hover:bg-orange-50/20 hover:border-orange-200 transition-colors"
                >
                  <div className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                    ✓
                  </div>
                  <div>
                    <p className="text-xs sm:text-sm font-semibold text-slate-700 leading-snug">
                      {benefit}
                    </p>
                  </div>
                </div>
              ))}
          </div>

          {/* Detailed Description */}
          {product.detailedDescription && (
            <div className="mt-8 pt-6 border-t border-slate-100">
              <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-2">
                Detailed Product Overview
              </h3>
              <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-normal">
                {product.detailedDescription}
              </p>
            </div>
          )}
        </div>

        {/* ========================================================================= */}
        {/* PRODUCT DEMONSTRATION VIDEO SECTION */}
        {/* ========================================================================= */}
        {product.video && (
          <ProductVideoShowcase video={product.video} productName={product.name} />
        )}

        {/* ========================================================================= */}
        {/* SPECIFICATIONS SECTION (Amazon-Inspired Tabular Layout) */}
        {/* ========================================================================= */}
        <div className="bg-white rounded-3xl border border-slate-200/80 p-6 sm:p-8 lg:p-10 shadow-sm mb-10">
          <div className="flex items-center gap-2 mb-2">
            <FileText className="w-5 h-5 text-orange-500" />
            <span className="text-xs font-black text-slate-400 uppercase tracking-widest">
              TECHNICAL SPECIFICATIONS
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black font-display text-slate-900 tracking-tight mb-6">
            Specifications
          </h2>

          <div className="border border-slate-200 rounded-2xl overflow-hidden shadow-xs">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-100/80 text-slate-700 text-xs uppercase font-extrabold border-b border-slate-200">
                  <th className="py-3.5 px-4 sm:px-6 w-1/3 sm:w-1/4">
                    Specification
                  </th>
                  <th className="py-3.5 px-4 sm:px-6">Detail / Manufacturer Value</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-150 text-xs sm:text-sm text-slate-700">
                {/* Dynamically list ONLY existing specs */}
                {Object.entries(product.specs).map(([specKey, specVal], idx) => (
                  <tr
                    key={specKey}
                    className={idx % 2 === 0 ? "bg-white" : "bg-slate-50/50"}
                  >
                    <td className="py-3.5 px-4 sm:px-6 font-bold text-slate-900">
                      {specKey}
                    </td>
                    <td className="py-3.5 px-4 sm:px-6 font-semibold text-slate-700">
                      {specVal}
                    </td>
                  </tr>
                ))}

                {/* Show availableSizes if available */}
                {product.availableSizes && (
                  <tr className="bg-orange-50/30">
                    <td className="py-3.5 px-4 sm:px-6 font-bold text-slate-900">
                      Available Sizes Range
                    </td>
                    <td className="py-3.5 px-4 sm:px-6 font-bold text-orange-700">
                      {product.availableSizes}
                    </td>
                  </tr>
                )}

                {/* Show commonSizes if available */}
                {product.commonSizes && product.commonSizes.length > 0 && (
                  <tr className="bg-white">
                    <td className="py-3.5 px-4 sm:px-6 font-bold text-slate-900">
                      Common Ready Sizes
                    </td>
                    <td className="py-3.5 px-4 sm:px-6 font-medium text-slate-700">
                      {product.commonSizes.join(", ")}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* ========================================================================= */}
        {/* APPLICATIONS SECTION */}
        {/* ========================================================================= */}
        <div className="bg-white rounded-3xl border border-slate-200/80 p-6 sm:p-8 lg:p-10 shadow-sm mb-10">
          <div className="flex items-center gap-2 mb-2">
            <Building className="w-5 h-5 text-orange-500" />
            <span className="text-xs font-black text-slate-400 uppercase tracking-widest">
              USE CASES
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black font-display text-slate-900 tracking-tight mb-6">
            Applications
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {product.applications.map((app, idx) => (
              <div
                key={idx}
                className="flex items-start gap-3.5 p-4 rounded-2xl bg-slate-50 border border-slate-150 hover:bg-slate-100/70 transition-colors"
              >
                <div className="w-10 h-10 rounded-xl bg-white border border-slate-200 flex items-center justify-center shrink-0 shadow-xs">
                  {getAppIcon(app)}
                </div>
                <div>
                  <h4 className="text-xs sm:text-sm font-bold text-slate-800 leading-snug">
                    {app}
                  </h4>
                  <p className="text-[11px] text-slate-500 mt-0.5">
                    Recommended for reliable protection and high durability.
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ========================================================================= */}
        {/* FAQS SECTION (if available) */}
        {/* ========================================================================= */}
        {product.faqs && product.faqs.length > 0 && (
          <div className="bg-white rounded-3xl border border-slate-200/80 p-6 sm:p-8 lg:p-10 shadow-sm mb-10">
            <div className="flex items-center gap-2 mb-2">
              <HelpCircle className="w-5 h-5 text-orange-500" />
              <span className="text-xs font-black text-slate-400 uppercase tracking-widest">
                FREQUENTLY ASKED QUESTIONS
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-black font-display text-slate-900 tracking-tight mb-6">
              Product Questions & Answers
            </h2>

            <div className="space-y-3">
              {product.faqs.map((faq, index) => {
                const isOpen = openFaqIdx === index;
                return (
                  <div
                    key={index}
                    className="border border-slate-200 rounded-2xl overflow-hidden transition-colors"
                  >
                    <button
                      onClick={() => setOpenFaqIdx(isOpen ? null : index)}
                      className="w-full text-left py-3.5 px-5 font-bold text-xs sm:text-sm text-slate-800 flex justify-between items-center bg-white hover:bg-slate-50/60 transition-colors cursor-pointer"
                    >
                      <span className="pr-4">{faq.question}</span>
                      <span className="text-orange-500 font-bold text-lg shrink-0">
                        {isOpen ? "−" : "+"}
                      </span>
                    </button>
                    {isOpen && (
                      <div className="p-5 text-xs sm:text-sm text-slate-600 leading-relaxed border-t border-slate-100 bg-slate-50">
                        {faq.answer}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* ========================================================================= */}
        {/* CUSTOMER REVIEWS & RATINGS SECTION (Product-Specific with 4.8 / 4.9 avg) */}
        {/* ========================================================================= */}
        <ProductReviewsSection
          productId={product.id}
          productName={product.name}
          onStatsChange={(newStats) => setRatingStats(newStats)}
        />

        {/* ========================================================================= */}
        {/* RELATED PRODUCTS SECTION ("Customers Also Viewed") */}
        {/* ========================================================================= */}
        <div className="mt-14 mb-10">
          <div className="flex flex-col mb-6 text-left">
            <span className="text-xs font-black text-slate-400 uppercase tracking-widest mb-1">
              RECOMMENDED FOR YOU
            </span>
            <h3 className="text-2xl sm:text-3xl font-black font-display text-slate-900 tracking-tight">
              Customers Also Viewed
            </h3>
            <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
              Explore similar tarpaulins, plastic rolls, and industrial polymer sheets.
            </p>
          </div>

          {/* DESKTOP & TABLET: 4-COLUMN HORIZONTAL GRID (Preserved as requested) */}
          <div className="hidden sm:grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {relatedProducts.slice(0, 4).map((p) => {
              const pStats = computeRatingStats(getAutoGeneratedReviews(p.id));
              const openProductPage = () => {
                const slug = getProductSlug(p.id);
                window.history.pushState({}, "", `/products/${slug}`);
                window.dispatchEvent(new Event("popstate"));
                window.scrollTo({ top: 0, behavior: "smooth" });
              };
              return (
                <div
                  key={p.id}
                  onClick={openProductPage}
                  className="bg-white rounded-2xl border border-slate-200/80 overflow-hidden shadow-xs hover:shadow-md hover:border-slate-300 transition-all flex flex-col group cursor-pointer"
                >
                  <div 
                    onClick={(e) => {
                      e.stopPropagation();
                      openProductPage();
                    }}
                    className="relative aspect-[4/3] bg-slate-100 overflow-hidden cursor-pointer"
                  >
                    <img
                      src={p.images[0]}
                      alt={p.name}
                      referrerPolicy="no-referrer"
                      className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105 cursor-pointer"
                    />
                    {p.isBestSeller && (
                      <span className="absolute top-2.5 left-2.5 bg-orange-500 text-white text-[10px] font-black px-2 py-0.5 rounded-md uppercase tracking-wider z-10 shadow-xs">
                        Best Seller
                      </span>
                    )}
                  </div>

                  <div className="p-4 flex flex-col flex-1 justify-between">
                    <div
                      onClick={(e) => {
                        e.stopPropagation();
                        openProductPage();
                      }}
                      className="cursor-pointer"
                    >
                      <span className="text-[10px] font-bold text-orange-600 uppercase tracking-wider block mb-1">
                        {p.category}
                      </span>
                      <h4 
                        onClick={(e) => {
                          e.stopPropagation();
                          openProductPage();
                        }}
                        className="font-extrabold text-slate-900 text-xs sm:text-sm line-clamp-1 group-hover:text-orange-600 transition-colors cursor-pointer"
                      >
                        {p.name}
                      </h4>

                      {/* Ratings 4.8 / 4.9 */}
                      <div className="flex items-center gap-1.5 mt-1.5 mb-1">
                        <div className="flex items-center text-amber-400">
                          {[1, 2, 3, 4, 5].map((s) => (
                            <Star
                              key={s}
                              className={`w-3 h-3 ${
                                s <= Math.round(pStats.average)
                                ? "fill-amber-400 text-amber-400"
                                : "text-slate-200"
                              }`}
                            />
                          ))}
                        </div>
                        <span className="text-[11px] font-bold text-slate-800">
                          {pStats.average.toFixed(1)}
                        </span>
                        <span className="text-[10px] text-slate-400">
                          ({pStats.totalCount})
                        </span>
                      </div>

                      <p className="text-[11px] text-slate-500 mt-1 line-clamp-2 leading-relaxed">
                        {p.description}
                      </p>
                    </div>

                    <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between gap-2">
                      <span
                        className={`text-[10px] font-bold px-2 py-0.5 rounded-md ${
                          p.id === "cosmetics-shringar"
                            ? "text-rose-700 bg-rose-50 border border-rose-200/60"
                            : "text-emerald-700 bg-emerald-50"
                        }`}
                      >
                        {p.id === "cosmetics-shringar"
                          ? "Retail Store Only"
                          : "Price on Enquiry"}
                      </span>
                      <a
                        href={`/products/${getProductSlug(p.id)}`}
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          openProductPage();
                        }}
                        className="text-xs font-bold text-orange-600 hover:text-orange-700 flex items-center gap-1 cursor-pointer"
                      >
                        <span>View Product</span>
                        <ChevronRight className="w-3.5 h-3.5" />
                      </a>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* MOBILE: AUTO-SCROLL ONE-BY-ONE CAROUSEL */}
          <div className="sm:hidden">
            <MobileRelatedProductsCarousel products={relatedProducts} />
          </div>
        </div>

        {/* STICKY BOTTOM MOBILE CTA BAR */}
        <div className="lg:hidden fixed bottom-0 left-0 right-0 z-40 bg-white/95 backdrop-blur-md border-t border-slate-200 px-4 py-3 shadow-lg flex items-center justify-between gap-3">
          <div className="flex flex-col max-w-[55%]">
            <span className="text-xs font-bold text-slate-900 truncate">
              {product.name}
            </span>
            <span
              className={`text-[11px] font-bold ${
                isCosmetics ? "text-rose-600" : "text-emerald-600"
              }`}
            >
              {isCosmetics ? "Retail Walk-in Store Only" : "Price on Enquiry"}
            </span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={toggleWishlist}
              className={`p-2.5 rounded-xl border transition-colors ${
                isInWishlist
                  ? "border-rose-300 bg-rose-50 text-rose-600"
                  : "border-slate-200 text-slate-600"
              }`}
              aria-label="Wishlist"
            >
              <Heart
                className={`w-4 h-4 ${
                  isInWishlist ? "fill-rose-500 text-rose-500" : ""
                }`}
              />
            </button>

            {isCosmetics ? (
              <span className="text-xs font-black text-rose-800 bg-rose-100 border border-rose-200 px-3 py-2 rounded-xl">
                Retail Only
              </span>
            ) : (
              <button
                onClick={() => setIsEnquiryModalOpen(true)}
                className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-orange-500 hover:bg-orange-600 active:scale-95 text-white font-black text-xs shadow-md"
              >
                <MessageSquare className="w-3.5 h-3.5 fill-current" />
                <span>ENQUIRE NOW</span>
              </button>
            )}
          </div>
        </div>

        {/* TYPEFORM-STYLE ENQUIRY MODAL (Disabled for Cosmetics items) */}
        {!isCosmetics && (
          <TypeformEnquiryModal
            isOpen={isEnquiryModalOpen}
            onClose={() => setIsEnquiryModalOpen(false)}
            product={{
              id: product.id,
              name: product.name,
              images: product.images,
              category: product.category,
            }}
          />
        )}
      </div>
    </div>
  );
}
